# Generated by Django 2.2 on 2019-10-01 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0004_areainfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areainfo',
            old_name='b_parent_id',
            new_name='b_parent',
        ),
    ]
