# Generated by Django 2.2 on 2019-10-01 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0005_auto_20191001_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areainfo',
            old_name='b_parent',
            new_name='a_parent',
        ),
        migrations.RenameField(
            model_name='areainfo',
            old_name='b_title',
            new_name='a_title',
        ),
    ]
