# Generated by Django 2.2 on 2019-11-25 13:19

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0006_auto_20191001_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_pic', models.ImageField(upload_to='booktest')),
            ],
        ),
        migrations.AlterModelManagers(
            name='bookinfo',
            managers=[
                ('books', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='areainfo',
            name='a_title',
            field=models.CharField(max_length=20, verbose_name='区域名称'),
        ),
    ]
